# Project is written in C++ (defines some useful defaults)
language: cpp

cache: ccache

# Save time by only getting the current repository status
git:
  depth: false

# Test both clang and gcc
compiler:
  - gcc
  - clang

# Test both linux and osx
os:
  - linux
  - osx
  - windows

env:
  - GENERATOR="Ninja"
  - GENERATOR="Unix Makefiles"

# Install requirements with apt
addons:
  apt:
    packages:
    - ncurses-dev
    - cmake
  homebrew:
    packages:
    - ncurses
    - cmake
    - ccache
    - python3

# Build Matrix
matrix:
  fast_finish: true
  exclude:
    - compiler: clang
      env: GENERATOR="Ninja"
    - os: windows
      env: GENERATOR="Unix Makefiles"
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - eval "${MATRIX_EVAL}"
# " Fixes Visual Studio highlighting

install:
  - ./travis-windows-setup.sh

before_script:
  - cmake --version
  - mkdir build && cd build

# Actually check if it works
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_PARALLEL_LEVEL=2 -DCMAKE_VERBOSE_MAKEFILE=TRUE ..
  - cmake --build .
  - ctest -j2 -VV
