language: c
git:
  depth: false
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - libncurses-dev
    - libxml2-dev
    - make
script:
  - tar zxf game-1.0.tar.gz && cd game-1.0 && ./configure && make && make check
