language: c
git:
  depth: false
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libncurses-dev libxml2-dev && sudo apt-get upgrade -y gcc
script:
  - tar zxf game-1.0.tar.gz && cd game-1.0 && ./configure && make && make check
